"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KYmeCgeQelg
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { FaGoogle } from "react-icons/fa";
import { AuthAction, handleAuthAction } from "@/app/(auth)/auth_action";
import { PATH } from "@/path";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { APP_NAME } from "@/config";
export function LoginPage() {
  const router = useRouter();
  const [error, setError] = useState<string>();

  const handleSignIn = async (action: AuthAction, data: FormData) => {
    const res = await handleAuthAction(action, data);
    if (res) {
      setError(res);
    } else {
      router.replace(PATH.FIND_USER);
    }
  };
  const googleAction = handleSignIn.bind(null, "google");
  const credentialAction = handleSignIn.bind(null, "credential");

  return (
    <div className="flex items-center justify-center h-[80svh] bg-gray-100 dark:bg-gray-950">
      <div className="w-full max-w-md p-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <div className="mb-6 text-center">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-50">
            Welcome to {APP_NAME}
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Sign in to your account
          </p>
        </div>
        <form className="space-y-4" action={credentialAction}>
          <div>
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              placeholder="Enter your email "
              required
              type="text"
              name="email"
            />
          </div>
          <div>
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              placeholder="Enter your password"
              required
              type="password"
              name="password"
            />
          </div>
          <small className="text-red-500">{error}</small>

          <Button className="w-full" type="submit">
            Login
          </Button>
        </form>
        <form action={googleAction}>
          <Button className="w-full mt-4" variant={"ghost"} type="submit">
            <FaGoogle className="size-6 mx-4" /> Sign In With Google
          </Button>
        </form>
        <div className="mt-6 text-center text-gray-600 dark:text-gray-400">
          {"Don't have an account?"}
          <Link
            className="font-medium text-blue-600 hover:underline dark:text-blue-500"
            href={PATH.SIGNUP}
          >
            Sign up
          </Link>
        </div>
      </div>
    </div>
  );
}
